name: ci

on:
  push:
    branches:
     - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:     
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --verbose --timeout 5m0s --config ./.golangci.yml